# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 867469a186dda42a746c8d1552c18fa1ab30b130fc46e5d1a42a476a063f1081a1bdef3744c3addb17c8741d9dcfc497620d6757a6946722d7686d8a724a150a
  paypal_host: https://www.sandbox.paypal.com
  app_host: https://da70d3dd.ngrok.io
test:
  secret_key_base: f752df9c7a6c2c627190a83739c405659b0483f252bbddac68457de4468f836d0931cc702114163aa829ea59a9d6887439f7ed782e240fda096325d927f876ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9a0a8b58dff4623caf093db17a389f47bfb4c3ec1dc017ec6d9bb3ab2bcf225f00e1ef912c245add155f6131fcc148bdedcd9d6fdb6d9c006f6217ee08f62646
  paypal_host: https://www.paypal.com
  app_host: https://afrikaasource.herokuapp.com/

  